fix: display basic error message for incorrect HIP compiler path
fix: quote string

diff --git a/bin/hipcc_cmake_linker_helper b/bin/hipcc_cmake_linker_helper
--- a/bin/hipcc_cmake_linker_helper
+++ b/bin/hipcc_cmake_linker_helper
@@ -3,6 +3,9 @@
 SOURCE="${BASH_SOURCE[0]}"
 HIP_PATH="$( command cd -P "$( dirname "$SOURCE" )/.." && pwd )"
 HIP_COMPILER=$(eval "$HIP_PATH/bin/hipconfig --compiler")
+if [[ "$HIP_COMPILER" =~ hcc|clang ]] && [[ ! -d "$1" ]]; then
+  echo "$(basename "$0"): error: HIP compiler path is not a directory" >&2 && exit 1
+fi
 if [ "$HIP_COMPILER" =  "hcc" ]; then
   HCC_HOME=$1 $HIP_PATH/bin/hipcc "${@:2}"
 elif [ "$HIP_COMPILER" = "clang" ]; then
